### PR TITLE
Changed name of variable and added ruby 1.9.2 encoding tag

### PR DESCRIPTION
**Pull request by basvodde**
Made 2 small changes:
1) Changed the names of 2 variables that caused a warning when running with Ruby 1.9.2. The variables hided an outer variable and renaming it solves this.
2) Added a UTF8 tag to the tests which allows the tests to run under 1.9.2

### CODE REVIEW

**Comment by Manfred** [comment]
Thanks for the patch! I won't have time to look at this in great detail until in a few weeks.

A word of caution, if you're planning on using digest authentication in production you probably want to implement checks against replay attacks.

In general basic auth over SSL is a more secure and better supported alternative.

**Comment by sferik** [comment]
:+1: Any chance of merging this and pushing a new gem release?

**Comment by Manfred** [comment]
Erik, I hope you're not using this gem for digest authentication because it's not complete. I've added you to the gem owner list and added you as contributor, please go ahead and release a new version.

**Comment by sferik** [comment]
@Manfred Thanks for adding me as a contributor and gem owner.

I recently pushed `oauth2` version 0.9.3, which [removes the dependency on the `httpauth` gem](https://github.com/intridea/oauth2/pull/138) that you submitted.

Despite this, some people may be stuck on an older version of `oauth2`, so I’ll push out [a new version of the `httpauth` gem](http://rubygems.org/gems/httpauth/versions/0.2.1). We’ll see how many downloads it gets.

**Comment by Manfred** [comment]
Ah, right, totally forgot about that. Thanks for your time!

**Pull request merged**
